Feature/ci packing
F-WuTS/libcreate pull request #2
Opened 2024-09-24 07:17 UTC by Kola50011

2024-09-25 11:09 UTC, christoph-heiss requested changes, later dismissed
Apart from the `-Werror` stuff, LGTM.

2024-09-25 11:09 UTC, christoph-heiss commented on .github/workflows/test.yaml
> +        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_CXX_FLAGS="-Werror"
I'd rather add the `-Werror` directly in the CMake setup add the top to the `add_compile_options(..)` call.

2024-09-25 11:09 UTC, christoph-heiss commented on ci/entrypoint.sh
> +cmake -B /libcreate/build -S /libcreate -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS='-Werror'
Same as above for the CI workflow

2024-09-25 11:19 UTC, christoph-heiss commented on CMakeLists.txt
>  add_compile_options(-Wall -Wextra -Wpedantic)
```suggestion
add_compile_options(-Wall -Wextra -Wpedantic -Werror)
```

2024-09-25 20:08 UTC, Kola50011 commented
Should be good now. Pls approve and merge

2024-09-26 07:17 UTC, christoph-heiss approved these changes

2024-09-26 07:18 UTC, merged